@startuml on-buildbot-comment
' For on-the-fly rendering of the latest version of this diagram, please visit:
' http://www.plantuml.com/plantuml/proxy?idx=0&src=https://raw.githubusercontent.com/kwk/buildbot-app/main/docs/media/on-buildbot-comment.puml&fmt=svg
'
' To generate a PNG diagram from this file follow these steps:
' $ wget -o plantuml.jar http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
' $ java -jar plantuml.jar -verbose on-buildbot-comment.puml

' Give calls and returns a number for easier referencing
autonumber

title
    Sequence diagram for executing builds on Buildbot
    initiated by a /buildbot comment in Github Pull Request
end title

' When you comment this out, you'll get the participants and actors repeated at
' the bottom which is nice for a big diagram
' skinparam style strictuml

skinparam monochrome false
skinparam SequenceBoxBackgroundColor #efefef
skinparam SequenceBoxBorderColor #aeaeae
skinparam roundcorner 20
skinparam SequenceGroupBackgroundColor #718fbf
skinparam SequenceGroupHeaderFontColor #ffffff
skinparam SequenceGroupBodyBackgroundColor #9dc1fc

actor "Alice" as alice

box "Github.com"
    participant "Github.com\n<b>Website</b>" as gh
    participant "Github.com\n<b>API</b>" as ghapi
end box

box "Public\nHTTP endpoint\n(e.g. ngrok)"
    queue "HTTP\nForwarder" as forwarder
end box

box "Localhost developer machine"
    participant "Buildbot\n<b>App</b>" as app
    participant "Buildbot\n<b>Master</b>" as master
    participant "Buildbot\n<b>Worker1</b>" as worker1
    participant "Buildbot\n<b>Worker2</b>" as worker2
    participant "Buildbot\n<b>Worker3</b>" as worker3
end box

' app -> forwarder : Register to receive events\n(only needed during\ndevelopment stage)
alice -> gh : Create PR comment:\n<b>/buildbot</b>
note left : <u>NOTE:</u> The semantics are not defined so\nI just picked a simple string\nto kick off the pipeline.
ghapi -> forwarder : [[https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment Send issue_comment Webhook]]
forwarder -> app : forward this\ninbound\nrequest\n(and the\nones below)
activate app
        app -> app : Comment body\nmatches pattern?
        
        group Feedback to Github User: "We've received your message and begin processing shortly"
            app -> ghapi : [[https://docs.github.com/en/rest/issues/comments#create-an-issue-comment Create PR comment]]\nto indicate responsiveness
            activate ghapi
                return HTTP 201 OK
            gh -> alice : Display comment
        end

        group Feedback to Github User: "A check was created for you"
            app -> ghapi : [[https://docs.github.com/en/rest/checks/runs#create-a-check-run Create check run]]\nin neutral state
            activate ghapi
                return HTTP 201 OK
            gh -> alice : Show check run on PR page\nunder the Buildbot App\n<i>check suite</i>
        end

        app -> master : <b>buildbot try</b>\ncommand
        activate master
            note right : <u>NOTE:</u> try-scheduler picks up buildrequest\n(executes delegation builder)\nand <i>triggers a builder</i> to execute build\non a worker. 
        app --> forwarder : HTTP 20X
    forwarder --> ghapi : HTTP 20X ()
deactivate app
        
activate master
    
    group Feedback to Github User: "A build has started" (First time the URL to buildbot is provided)
        master -> app : HttpStatusPush with updated status\ninformation about the build
        note left : <u>NOTE:</u> This is a buildbot service\nto update interested parties about\nupdates to builds.
        activate app
            app -> ghapi : Update check run and:\n* add build state to existing summary\n*adjust run state according to build result
            activate ghapi
                return HTTP 20X
            return HTTP 20X
        gh -> alice : Show updated check suite\n"Starting..."
    end
    
    master -> worker2 : execute build on\nchosen worker

    activate worker2
        ...Some time later...
        return "build failed"
    
    group Feedback to Github User: "Build finished"
        master -> app : HttpStatusPush with updated status\ninformation about the build
        activate app
            app -> ghapi : Update check run and:\n* add build state to existing summary\n*adjust run state according to build result
            activate ghapi
                return HTTP 20X
            return HTTP 20X
        gh -> alice : Show updated check suite\n"Failed..."
    end
    
    deactivate master

@enduml: